[project]
name = 'Tokenized-Inventory-Supplier-Collaboration-Platforms'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.supplier-manager-verification]
path = 'contracts/supplier-manager-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-manager-verification_]
path = 'contracts/supplier-manager-verification_.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
